apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config-map
  namespace: default
data:
  employee-database-name: employee_db
  department-database-name: department_db
  cluster-database-port: "5432"
  cluster-database-host: mypostgres-0.mypostgres
  department-service-host: http://department-svc
