apiVersion: apps/v1
kind: Deployment
metadata:
  name: departmentapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: departmentapp
  replicas: 1
  template:
    metadata:
      labels:
        app: departmentapp
    spec:
      containers:
        - name: departmentapp
          image: ankitkapadiaa/department-service:latest
          # imagePullPolicy: Never
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 20
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 20
            failureThreshold: 3
            successThreshold: 1
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: cluster-config-map
                  key: cluster-database-host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: cluster-config-map
                  key: cluster-database-port
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: cluster-config-map
                  key: department-database-name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: postgres-password
          ports:
            - containerPort: 8090
              name: departmentapp
          restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: department-lb
  namespace: default
spec:
  selector:
    app: departmentapp
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8090
      name: departmentapp

---
apiVersion: v1
kind: Service
metadata:
  name: department-svc
  namespace: default
spec:
  selector:
    app: departmentapp
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8090
      name: departmentapp
